wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    t:
      1:
      - 1
      2:
      - 1
      4: 3.7.4
      5: 0.10.30
      8:
      - 5
activation function:
  desc: null
  value: leakyrelu
algorithm:
  desc: null
  value: BP
batch_size:
  desc: null
  value: 255
depth:
  desc: null
  value: 4
epochs:
  desc: null
  value: 100
hid_dim:
  desc: null
  value: 638
in_dim:
  desc: null
  value: 784
learning_rate:
  desc: null
  value: 0.05581466570345029
out_dim:
  desc: null
  value: 10
problem:
  desc: null
  value: classification-70000
seed:
  desc: null
  value: 39
